<?php
/**
 * Created by PhpStorm.
 * User: htwy
 * Date: 2017/6/16
 * Time: 15:18
 */

namespace app\models;

use yii\db\ActiveRecord;

class OrderDetail extends ActiveRecord
{
    public function rules()
    {
        return [
            [['productid', 'productnum', 'price', 'orderid', 'createtime'],'required'],
        ];
    }

    public static function tableName()
    {
        return parent::tableName(); // TODO: Change the autogenerated stub
    }

    public function add($data)
    {
        if ($this->load($data) && $this->save()) {
            return true;
        }
        return false;
    }
}