<?php
/**
 * Created by PhpStorm.
 * User: htwy
 * Date: 2017/6/2
 * Time: 10:35
 */

namespace app\models;

use yii\db\ActiveRecord;

class Test extends ActiveRecord
{
    public static function tableName()
    {
        return '{{%test}}';  //替换表前缀
        return parent::tableName(); // TODO: Change the autogenerated stub
    }
}